const lootItems = [
    { id: 1, name: "Snap Hook", price: 14000, tier: "S", kr_name: "스냅 훅" },
    { id: 2, name: "Queen Reactor", price: 13000, tier: "S", kr_name: "퀸 원자로" },
    { id: 3, name: "Matriarch Reactor", price: 13000, tier: "S", kr_name: "마트리아크 원자로" },
    { id: 4, name: "Lance's Mixtape (5th Edition)", price: 10000, tier: "S", kr_name: "랜스의 믹스테이프(5차 에디션)" },
    { id: 5, name: "Kinetic Converter", price: 7000, tier: "S", kr_name: "키네틱 컨버터" },
    { id: 6, name: "Anvil Splitter", price: 7000, tier: "S", kr_name: "앤빌 스플리터" },
    { id: 7, name: "Breathtaking Snow Globe", price: 7000, tier: "S", kr_name: "숨막히는 스노우 글로브" },
    { id: 8, name: "Horizontal Grip", price: 7000, tier: "S", kr_name: "수평 그립" },
    { id: 9, name: "Silencer III", price: 7000, tier: "S", kr_name: "소음기 III" },
    { id: 10, name: "Ion Sputter", price: 6000, tier: "S", kr_name: "이온 스퍼터" },
    { id: 11, name: "Magnetron", price: 6000, tier: "S", kr_name: "전자관" },
    { id: 12, name: "Magnetic Accelerator", price: 5500, tier: "S", kr_name: "자성 가속기" },
    { id: 13, name: "Power Rod", price: 5500, tier: "S", kr_name: "파워 로드" },
    { id: 14, name: "Heavy Shield", price: 5500, tier: "S", kr_name: "중량 실드" },
    { id: 15, name: "Explosive Mine Blueprint", price: 5000, tier: "S", kr_name: "폭발 지뢰 설계도" },
    { id: 16, name: "Smoke Grenade Blueprint", price: 5000, tier: "S", kr_name: "연막 수류탄 설계도" },
    { id: 17, name: "Leaper Pulse Unit", price: 5000, tier: "S", kr_name: "리퍼 펄스 유닛" },
    { id: 18, name: "Light Gun Parts Blueprint", price: 5000, tier: "S", kr_name: "경량 총기 부품 설계도" },
    { id: 19, name: "Tactical Mk. 3 (Healing)", price: 5000, tier: "S", kr_name: "전술 마크 3(치유)" },
    { id: 20, name: "Torrente Blueprint", price: 5000, tier: "S", kr_name: "토렌테 설계도" },
    { id: 21, name: "Venator Blueprint", price: 5000, tier: "S", kr_name: "베나토르 설계도" },
    { id: 22, name: "Tactical MK.3 (Defensive) Blueprint", price: 5000, tier: "S", kr_name: "전술 마크 3(방어) 설계도" },
    { id: 23, name: "Angled Grip II Blueprint", price: 5000, tier: "S", kr_name: "앵글 그립 II 설계도" },
    { id: 24, name: "Looting MK. 3 (Survivor)", price: 5000, tier: "S", kr_name: "노획 마크 3(생존자)" },
    { id: 25, name: "Launcher Ammo Blueprint", price: 5000, tier: "S", kr_name: "발사기 탄약 설계도" },
    { id: 26, name: "Blue Light Stick Blueprint", price: 5000, tier: "S", kr_name: "파란색 야광봉 설계도" },
    { id: 27, name: "Angled Grip III", price: 5000, tier: "S", kr_name: "앵글 그립 III" },
    { id: 28, name: "Wolfpack Blueprint", price: 5000, tier: "S", kr_name: "울프팩 설계도" },
    { id: 29, name: "Shotgun Choke III", price: 5000, tier: "S", kr_name: "산탄총 초크 III" },
    { id: 30, name: "Red Light Stick Blueprint", price: 5000, tier: "S", kr_name: "빨간색 야광봉 설계도" },
    { id: 31, name: "Lightweight Stock", price: 5000, tier: "S", kr_name: "경량 개머리판" },
    { id: 32, name: "Anvil Splitter Blueprint", price: 5000, tier: "S", kr_name: "앤빌 스플리터 설계도" },
    { id: 33, name: "Green Light Stick Blueprint", price: 5000, tier: "S", kr_name: "초록색 야광봉 설계도" },
    { id: 34, name: "Barricade Kit Blueprint", price: 5000, tier: "S", kr_name: "바리케이드 키트 설계도" },
    { id: 35, name: "Compensator III Blueprint", price: 5000, tier: "S", kr_name: "총구 보정기 III 설계도" },
    { id: 36, name: "Vulcano Blueprint", price: 5000, tier: "S", kr_name: "불카노 설계도" },
    { id: 37, name: "Shotgun Choke II Blueprint", price: 5000, tier: "S", kr_name: "산탄총 초크 II 설계도" },
    { id: 38, name: "Music Box", price: 5000, tier: "S", kr_name: "뮤직 박스" },
    { id: 39, name: "Looting MK. 3 (Survivor) Blueprint", price: 5000, tier: "S", kr_name: "노획 마크 3(생존자) 설계도" },
    { id: 40, name: "Red Coral Jewelry", price: 5000, tier: "S", kr_name: "붉은 산호 장신구" },
    { id: 41, name: "Heavy Fuse Grenade Blueprint", price: 5000, tier: "S", kr_name: "중량 신관 수류탄 설계도" },
    { id: 42, name: "Lure Grenade Blueprint", price: 5000, tier: "S", kr_name: "유인 수류탄 설계도" },
    { id: 43, name: "Looting MK. 3 (Cautious)", price: 5000, tier: "S", kr_name: "노획 마크 3(신중)" },
    { id: 44, name: "Aphelion Rifle Blueprint", price: 5000, tier: "S", kr_name: "아펠리온 소총 설계도" },
    { id: 45, name: "Combat Mk. 3 (Flanking) Blueprint", price: 5000, tier: "S", kr_name: "전투 마크 3(측면 기동) 설계도" },
    { id: 46, name: "Combat Mk.3 (Aggressive) Blueprint", price: 5000, tier: "S", kr_name: "전투 마크 3(공격적) 설계도" },
    { id: 47, name: "Hullcracker Blueprint", price: 5000, tier: "S", kr_name: "헐크래커 설계도" },
    { id: 48, name: "Blaze Grenade Blueprint", price: 5000, tier: "S", kr_name: "화염 수류탄 설계도" },
    { id: 49, name: "Shotgun Silencer Blueprint", price: 5000, tier: "S", kr_name: "산탄총 소음기 설계도" },
    { id: 50, name: "Extended Light Mag II Blueprint", price: 5000, tier: "S", kr_name: "확장형 경량 탄창 II 설계도" },
    { id: 51, name: "Complex Gun Parts Blueprint", price: 5000, tier: "S", kr_name: "정교한 총기 부품 설계도" },
    { id: 52, name: "Extended Medium Mag III Blueprint", price: 5000, tier: "S", kr_name: "확장형 준중량 탄창 III 설계도" },
    { id: 53, name: "Shotgun Choke III Blueprint", price: 5000, tier: "S", kr_name: "산탄총 초크 III 설계도" },
    { id: 54, name: "Bettina Blueprint", price: 5000, tier: "S", kr_name: "베티나 설계도" },
    { id: 55, name: "Silencer I Blueprint", price: 5000, tier: "S", kr_name: "소음기 I 설계도" },
    { id: 56, name: "Vertical Grip III Blueprint", price: 5000, tier: "S", kr_name: "수직 그립 III 설계도" },
    { id: 57, name: "Stable Stock III Blueprint", price: 5000, tier: "S", kr_name: "안정형 개머리판 III 설계도" },
    { id: 58, name: "Tactical MK.3 (Healing) Blueprint", price: 5000, tier: "S", kr_name: "전술 마크 3(치유) 설계도" },
    { id: 59, name: "not-in-game-Deadline Blueprint", price: 5000, tier: "S", kr_name: "미사용-데드라인 설계도" },
    { id: 60, name: "Combat Mk. 3 (Flanking)", price: 5000, tier: "S", kr_name: "전투 마크 3(측면 기동)" },
    { id: 61, name: "Tempest I Blueprint", price: 5000, tier: "S", kr_name: "템페스트 설계도" },
    { id: 62, name: "Heavy Gun Parts Blueprint", price: 5000, tier: "S", kr_name: "중량 총기 부품 설계도" },
    { id: 63, name: "Showstopper Blueprint", price: 5000, tier: "S", kr_name: "쇼스토퍼 설계도" },
    { id: 64, name: "Remote Raider Flare Blueprint", price: 5000, tier: "S", kr_name: "원격 레이더 조명탄 설계도" },
    { id: 65, name: "Playing Cards", price: 5000, tier: "S", kr_name: "트럼프 카드" },
    { id: 66, name: "Yellow Light Stick Blueprint", price: 5000, tier: "S", kr_name: "노란색 야광봉 설계도" },
    { id: 67, name: "Angled Grip III Blueprint", price: 5000, tier: "S", kr_name: "앵글 그립 III 설계도" },
    { id: 68, name: "Tactical Mk.3 (Defensive)", price: 5000, tier: "S", kr_name: "전술 마크 3(방어)" },
    { id: 69, name: "Bastion Cell", price: 5000, tier: "S", kr_name: "바스티온 전지" },
    { id: 70, name: "WolfPack", price: 5000, tier: "S", kr_name: "울프팩" },
    { id: 71, name: "Shotgun Silencer", price: 5000, tier: "S", kr_name: "산탄총 소음기" },
    { id: 72, name: "Compensator III", price: 5000, tier: "S", kr_name: "총구 보정기 III" },
    { id: 73, name: "Combat Mk. 3 (Aggressive)", price: 5000, tier: "S", kr_name: "전투 마크 3(공격적)" },
    { id: 74, name: "Anvil Blueprint", price: 5000, tier: "S", kr_name: "앤빌 설계도" },
    { id: 75, name: "Extended Shotgun Mag II Blueprint", price: 5000, tier: "S", kr_name: "확장형 산탄총 탄창 II 설계도" },
    { id: 76, name: "Horizontal Grip Blueprint", price: 5000, tier: "S", kr_name: "수평 그립 설계도" },
    { id: 77, name: "Osprey Blueprint", price: 5000, tier: "S", kr_name: "오스프레이 설계도" },
    { id: 78, name: "Vita Shot Blueprint", price: 5000, tier: "S", kr_name: "회복 주사 설계도" },
    { id: 79, name: "Defibrillator Blueprint", price: 5000, tier: "S", kr_name: "제세동기 설계도" },
    { id: 80, name: "Deadline", price: 5000, tier: "S", kr_name: "데드라인" },
    { id: 81, name: "Il Toro Blueprint", price: 5000, tier: "S", kr_name: "일 토로 설계도" },
    { id: 82, name: "Energy Ammo Blueprint", price: 5000, tier: "S", kr_name: "에너지 탄약 설계도" },
    { id: 83, name: "Vita Spray Blueprint", price: 5000, tier: "S", kr_name: "회복 스프레이 설계도" },
    { id: 84, name: "Jupiter Blueprint", price: 5000, tier: "S", kr_name: "주피터 설계도" },
    { id: 85, name: "Stable Stock II Blueprint", price: 5000, tier: "S", kr_name: "안정형 개머리판 II 설계도" },
    { id: 86, name: "Compensator II Blueprint", price: 5000, tier: "S", kr_name: "총구 보정기 II 설계도" },
    { id: 87, name: "Equalizer Blueprint", price: 5000, tier: "S", kr_name: "이퀄라이저 설계도" },
    { id: 88, name: "Trigger Nade Blueprint", price: 5000, tier: "S", kr_name: "트리거 수류탄 설계도" },
    { id: 89, name: "Bombardier Cell", price: 5000, tier: "S", kr_name: "봄바디어 전지" },
    { id: 90, name: "Extended Barrel", price: 5000, tier: "S", kr_name: "확장형 총열" },
    { id: 91, name: "Door Blocker Blueprint", price: 5000, tier: "S", kr_name: "문 차단기 설계도" },
    { id: 92, name: "Jolt Mine Blueprint", price: 5000, tier: "S", kr_name: "충격 지뢰 설계도" },
    { id: 93, name: "Extended Shotgun Mag III Blueprint", price: 5000, tier: "S", kr_name: "확장형 산탄총 탄창 III 설계도" },
    { id: 94, name: "Rocketeer Driver", price: 5000, tier: "S", kr_name: "로켓티어 드라이버" },
    { id: 95, name: "Padded Stock Blueprint", price: 5000, tier: "S", kr_name: "패딩 개머리판 설계도" },
    { id: 96, name: "Stable Stock III", price: 5000, tier: "S", kr_name: "안정형 개머리판 III" },
    { id: 97, name: "Bobcat Blueprint", price: 5000, tier: "S", kr_name: "밥캣 설계도" },
    { id: 98, name: "Snap Hook Blueprint", price: 5000, tier: "S", kr_name: "스냅 훅 설계도" },
    { id: 99, name: "Silencer II Blueprint", price: 5000, tier: "S", kr_name: "소음기 II 설계도" },
    { id: 100, name: "Burletta Blueprint", price: 5000, tier: "S", kr_name: "부를레타 설계도" },
    { id: 101, name: "Photoelectric Cloak", price: 5000, tier: "S", kr_name: "광전자 망토" },
    { id: 102, name: "Extended Medium Mag II Blueprint", price: 5000, tier: "S", kr_name: "확장형 준중량 탄창 II 설계도" },
    { id: 103, name: "Silencer II", price: 5000, tier: "S", kr_name: "소음기 II" },
    { id: 104, name: "Extended Light Mag III Blueprint", price: 5000, tier: "S", kr_name: "확장형 경량 탄창 III 설계도" },
    { id: 105, name: "Extended Barrel Blueprint", price: 5000, tier: "S", kr_name: "확장형 총열 설계도" },
    { id: 106, name: "Muzzle Brake II Blueprint", price: 5000, tier: "S", kr_name: "총구 제동기 II 설계도" },
    { id: 107, name: "Lightweight Stock Blueprint", price: 5000, tier: "S", kr_name: "경량 개머리판 설계도" },
    { id: 108, name: "Medium Gun Parts Blueprint", price: 5000, tier: "S", kr_name: "준중량 총기 부품 설계도" },
    { id: 109, name: "Muzzle Brake III Blueprint", price: 5000, tier: "S", kr_name: "총구 제동기 III 설계도" },
    { id: 110, name: "Silencer III Blueprint", price: 5000, tier: "S", kr_name: "소음기 III 설계도" },
    { id: 111, name: "Tagging Grenade Blueprint", price: 5000, tier: "S", kr_name: "표식 수류탄 설계도" },
    { id: 112, name: "Vertical Grip II Blueprint", price: 5000, tier: "S", kr_name: "수직 그립 II 설계도" },
    { id: 113, name: "Spectrum Analyzer", price: 3500, tier: "A", kr_name: "스펙트럼 분석기" },
    { id: 114, name: "Geiger Counter", price: 3500, tier: "A", kr_name: "가이거 계수기" },
    { id: 115, name: "Silver Teaspoon Set", price: 3000, tier: "A", kr_name: "은제 티스푼 세트" },
    { id: 116, name: "Statuette", price: 3000, tier: "A", kr_name: "소형 조각상" },
    { id: 117, name: "Flow Controller", price: 3000, tier: "A", kr_name: "유량 조절기" },
    { id: 118, name: "Microscope", price: 3000, tier: "A", kr_name: "현미경" },
    { id: 119, name: "Radio Relay", price: 3000, tier: "A", kr_name: "라디오 중계기" },
    { id: 120, name: "Sample Cleaner", price: 3000, tier: "A", kr_name: "샘플 클리너" },
    { id: 121, name: "Music Album", price: 3000, tier: "A", kr_name: "음반" },
    { id: 122, name: "Frequency Modulation Box", price: 3000, tier: "A", kr_name: "주파수 변조 박스" },
    { id: 123, name: "Fine Wristwatch", price: 3000, tier: "A", kr_name: "고급 손목시계" },
    { id: 124, name: "Spectrometer", price: 3000, tier: "A", kr_name: "분광계" },
    { id: 125, name: "Mini Centrifuge", price: 3000, tier: "A", kr_name: "미니 원심분리기" },
    { id: 126, name: "Shredder Gyro", price: 3000, tier: "A", kr_name: "슈레더 자이로" },
    { id: 127, name: "Signal Amplifier", price: 3000, tier: "A", kr_name: "신호 증폭기" },
    { id: 128, name: "Rotary Encoder", price: 3000, tier: "A", kr_name: "회전형 인코더" },
    { id: 129, name: "Vase", price: 3000, tier: "A", kr_name: "꽃병" },
    { id: 130, name: "Telemetry Transceiver", price: 3000, tier: "A", kr_name: "텔레메트리 트랜시버" },
    { id: 131, name: "Complex Gun Parts", price: 3000, tier: "A", kr_name: "정교한 총기 부품" },
    { id: 132, name: "Sentinel Firing Core", price: 3000, tier: "A", kr_name: "센티넬 발사 코어" },
    { id: 133, name: "Vita Spray", price: 2880, tier: "B", kr_name: "회복 스프레이" },
    { id: 134, name: "Exodus Modules", price: 2750, tier: "B", kr_name: "엑소더스 모듈" },
    { id: 135, name: "Bison Driver", price: 2500, tier: "B", kr_name: "바이슨 드라이버" },
    { id: 136, name: "Showstopper", price: 2200, tier: "B", kr_name: "쇼스토퍼" },
    { id: 137, name: "Pottery", price: 2000, tier: "B", kr_name: "도자기" },
    { id: 138, name: "Very Comfortable Pillow", price: 2000, tier: "B", kr_name: "매우 편안한 베개" },
    { id: 139, name: "Turbo Pump", price: 2000, tier: "B", kr_name: "터보 펌프" },
    { id: 140, name: "Laboratory Reagents", price: 2000, tier: "B", kr_name: "연구실 시약" },
    { id: 141, name: "Extended Light Mag II", price: 2000, tier: "B", kr_name: "확장형 경량 탄창 II" },
    { id: 142, name: "Poster of Natural Wonder", price: 2000, tier: "B", kr_name: "자연 경관 포스터" },
    { id: 143, name: "Looting Mk. 2", price: 2000, tier: "B", kr_name: "노획 마크 2" },
    { id: 144, name: "Tactical Mk. 2", price: 2000, tier: "B", kr_name: "전술 마크 2" },
    { id: 145, name: "Film Reel", price: 2000, tier: "B", kr_name: "필름 릴" },
    { id: 146, name: "Painted Box", price: 2000, tier: "B", kr_name: "채색된 상자" },
    { id: 147, name: "Snitch Scanner", price: 2000, tier: "B", kr_name: "스니치 스캐너" },
    { id: 148, name: "Damaged Rocketeer Driver", price: 2000, tier: "B", kr_name: "손상된 로켓티어 드라이버" },
    { id: 149, name: "Cooling Fan", price: 2000, tier: "B", kr_name: "냉각팬" },
    { id: 150, name: "Stable Stock II", price: 2000, tier: "B", kr_name: "안정형 개머리판 II" },
    { id: 151, name: "Air Freshener", price: 2000, tier: "B", kr_name: "방향제" },
    { id: 152, name: "Shotgun Choke II", price: 2000, tier: "B", kr_name: "산탄총 초크 II" },
    { id: 153, name: "Medium Shield", price: 2000, tier: "B", kr_name: "준중량 실드" },
    { id: 154, name: "Combat Mk. 2", price: 2000, tier: "B", kr_name: "전투 마크 2" },
    { id: 155, name: "Raider Hatch Key", price: 2000, tier: "B", kr_name: "레이더 해치 열쇠" },
    { id: 156, name: "Compensator II", price: 2000, tier: "B", kr_name: "총구 보정기 II" },
    { id: 157, name: "Light Bulb", price: 2000, tier: "B", kr_name: "전구" },
    { id: 158, name: "Unusable Weapon", price: 2000, tier: "B", kr_name: "사용 불가능한 무기" },
    { id: 159, name: "Sterilized Bandage", price: 2000, tier: "B", kr_name: "멸균 붕대" },
    { id: 160, name: "Rocket Thruster", price: 2000, tier: "B", kr_name: "로켓 추진기" },
    { id: 161, name: "Hornet Driver", price: 2000, tier: "B", kr_name: "호넷 드라이버" },
    { id: 162, name: "Extended Medium Mag II", price: 2000, tier: "B", kr_name: "확장형 준중량 탄창 II" },
    { id: 163, name: "Dart Board", price: 2000, tier: "B", kr_name: "다트판" },
    { id: 164, name: "Motor", price: 2000, tier: "B", kr_name: "모터" },
    { id: 165, name: "Broken Guidance System", price: 2000, tier: "B", kr_name: "고장난 유도 시스템" },
    { id: 166, name: "Muzzle Brake II", price: 2000, tier: "B", kr_name: "총구 제동기 II" },
    { id: 167, name: "Spring Cushion", price: 2000, tier: "B", kr_name: "스프링 쿠션" },
    { id: 168, name: "Bicycle Pump", price: 2000, tier: "B", kr_name: "자전거 펌프" },
    { id: 169, name: "Ruined Accordion", price: 2000, tier: "B", kr_name: "망가진 아코디언" },
    { id: 170, name: "Portable TV", price: 2000, tier: "B", kr_name: "휴대용 TV" },
    { id: 171, name: "Fried Motherboard", price: 2000, tier: "B", kr_name: "타버린 메인보드" },
    { id: 172, name: "Extended Shotgun Mag II", price: 2000, tier: "B", kr_name: "확장형 산탄총 탄창 II" },
    { id: 173, name: "Spotter Relay", price: 2000, tier: "B", kr_name: "관측병 중계기" },
    { id: 174, name: "Vita Shot", price: 2000, tier: "B", kr_name: "회복 주사" },
    { id: 175, name: "Broken Handheld Radio", price: 2000, tier: "B", kr_name: "고장난 휴대용 라디오" },
    { id: 176, name: "Rosary", price: 2000, tier: "B", kr_name: "묵주" },
    { id: 177, name: "Rusted Shut Medical Kit", price: 2000, tier: "B", kr_name: "닫혀 있는 녹슨 의료용품 상자" },
    { id: 178, name: "Vertical Grip II", price: 2000, tier: "B", kr_name: "수직 그립 II" },
    { id: 179, name: "Surveyor Vault", price: 2000, tier: "B", kr_name: "서베이어 볼트" },
    { id: 180, name: "Rusted Gear", price: 2000, tier: "B", kr_name: "녹슨 톱니바퀴" },
    { id: 181, name: "Advanced Electrical Components", price: 1750, tier: "B", kr_name: "고급 전기 부품" },
    { id: 182, name: "Mod Components", price: 1750, tier: "B", kr_name: "모드 부품" },
    { id: 183, name: "Advanced Mechanical Components", price: 1750, tier: "B", kr_name: "고급 기계 부품" },
    { id: 184, name: "Blaze Grenade", price: 1600, tier: "B", kr_name: "화염 수류탄" },
    { id: 185, name: "Heavy Fuze Grenade", price: 1600, tier: "B", kr_name: "중량 신관 수류탄" },
    { id: 186, name: "Trailblazer Grenade", price: 1600, tier: "B", kr_name: "개척자 수류탄" },
    { id: 187, name: "Explosive Mine", price: 1500, tier: "B", kr_name: "폭발 지뢰" },
    { id: 188, name: "Surge Shield Recharger", price: 1200, tier: "B", kr_name: "급속 실드 충전기" },
    { id: 189, name: "ARC Flex Rubber", price: 1000, tier: "C", kr_name: "아크 플렉스 고무" },
    { id: 190, name: "Broken Flashlight", price: 1000, tier: "C", kr_name: "부서진 손전등" },
    { id: 191, name: "Torn Book", price: 1000, tier: "C", kr_name: "찢어진 책" },
    { id: 192, name: "Explosive Compound", price: 1000, tier: "C", kr_name: "혼합 화약" },
    { id: 193, name: "Lure Grenade", price: 1000, tier: "C", kr_name: "유인 수류탄" },
    { id: 194, name: "Remote Control", price: 1000, tier: "C", kr_name: "리모컨" },
    { id: 195, name: "Garlic Press", price: 1000, tier: "C", kr_name: "마늘 다지개" },
    { id: 196, name: "Bloated Tuna Can", price: 1000, tier: "C", kr_name: "부풀어 오른 참치캔" },
    { id: 197, name: "Projector", price: 1000, tier: "C", kr_name: "프로젝터" },
    { id: 198, name: "Blaze Grenade Trap", price: 1000, tier: "C", kr_name: "화염 수류탄 트랩" },
    { id: 199, name: "Coffee Pot", price: 1000, tier: "C", kr_name: "커피포트" },
    { id: 200, name: "Broken Riot Shield", price: 1000, tier: "C", kr_name: "고장난 폭동 진압 방패" },
    { id: 201, name: "Zipline", price: 1000, tier: "C", kr_name: "집라인" },
    { id: 202, name: "Water Filter", price: 1000, tier: "C", kr_name: "물 필터" },
    { id: 203, name: "Expired Pasta", price: 1000, tier: "C", kr_name: "유통기한 지난 파스타" },
    { id: 204, name: "Cat Bed", price: 1000, tier: "C", kr_name: "고양이 침대" },
    { id: 205, name: "Alarm Clock", price: 1000, tier: "C", kr_name: "알람 시계" },
    { id: 206, name: "Antiseptic", price: 1000, tier: "C", kr_name: "소독약" },
    { id: 207, name: "Rusted Tools", price: 1000, tier: "C", kr_name: "녹슨 도구" },
    { id: 208, name: "Recorder", price: 1000, tier: "C", kr_name: "녹음기" },
    { id: 209, name: "Smoke Grenade", price: 1000, tier: "C", kr_name: "연막 수류탄" },
    { id: 210, name: "Deflated Football", price: 1000, tier: "C", kr_name: "바람 빠진 축구공" },
    { id: 211, name: "ARC Motion Core", price: 1000, tier: "C", kr_name: "아크 모션 코어" },
    { id: 212, name: "ARC Circuitry", price: 1000, tier: "C", kr_name: "아크 전기회로망" },
    { id: 213, name: "Water Pump", price: 1000, tier: "C", kr_name: "물 펌프" },
    { id: 214, name: "Industrial Battery", price: 1000, tier: "C", kr_name: "산업용 배터리" },
    { id: 215, name: "Ripped Safety Vest", price: 1000, tier: "C", kr_name: "찢어진 안전 조끼" },
    { id: 216, name: "Rubber Duck", price: 1000, tier: "C", kr_name: "고무 오리" },
    { id: 217, name: "Tagging Grenade", price: 1000, tier: "C", kr_name: "표식 수류탄" },
    { id: 218, name: "Cooling Coil", price: 1000, tier: "C", kr_name: "냉각 코일" },
    { id: 219, name: "Broken Taser", price: 1000, tier: "C", kr_name: "고장난 테이저건" },
    { id: 220, name: "Thermostat", price: 1000, tier: "C", kr_name: "온도 조절 장치" },
    { id: 221, name: "Fertilizer", price: 1000, tier: "C", kr_name: "비료" },
    { id: 222, name: "Radio", price: 1000, tier: "C", kr_name: "라디오" },
    { id: 223, name: "Toaster", price: 1000, tier: "C", kr_name: "토스트기" },
    { id: 224, name: "Rubber Pad", price: 1000, tier: "C", kr_name: "고무 패드" },
    { id: 225, name: "Ruined Riot Shield", price: 1000, tier: "C", kr_name: "망가진 폭동 진압 방패" },
    { id: 226, name: "Agave", price: 1000, tier: "C", kr_name: "아가베" },
    { id: 227, name: "Wasp Driver", price: 1000, tier: "C", kr_name: "와스프 드라이버" },
    { id: 228, name: "Power Cable", price: 1000, tier: "C", kr_name: "전원 케이블" },
    { id: 229, name: "Damaged Heat Sink", price: 1000, tier: "C", kr_name: "손상된 방열판" },
    { id: 230, name: "Polluted Air Filter", price: 1000, tier: "C", kr_name: "오염된 공기 필터" },
    { id: 231, name: "ARC Synthetic Resin", price: 1000, tier: "C", kr_name: "아크 합성수지" },
    { id: 232, name: "Resin", price: 1000, tier: "C", kr_name: "수지" },
    { id: 233, name: "Coolant", price: 1000, tier: "C", kr_name: "냉각수" },
    { id: 234, name: "Industrial Magnet", price: 1000, tier: "C", kr_name: "산업용 자석" },
    { id: 235, name: "Cracked Bioscanner", price: 1000, tier: "C", kr_name: "깨진 바이오스캐너" },
    { id: 236, name: "Industrial Charger", price: 1000, tier: "C", kr_name: "산업용 충전기" },
    { id: 237, name: "ARC Thermo Lining", price: 1000, tier: "C", kr_name: "아크 발열 안감" },
    { id: 238, name: "Humidifier", price: 1000, tier: "C", kr_name: "가습기" },
    { id: 239, name: "ARC Performance Steel", price: 1000, tier: "C", kr_name: "아크 고강도 강철" },
    { id: 240, name: "Headphones", price: 1000, tier: "C", kr_name: "헤드폰" },
    { id: 241, name: "ARC Coolant", price: 1000, tier: "C", kr_name: "아크 냉각수" },
    { id: 242, name: "Empty Wine Bottle", price: 1000, tier: "C", kr_name: "빈 와인병" },
    { id: 243, name: "Power Bank", price: 1000, tier: "C", kr_name: "보조 배터리" },
    { id: 244, name: "Mushroom", price: 1000, tier: "C", kr_name: "버섯" },
    { id: 245, name: "Defibrillator", price: 1000, tier: "C", kr_name: "제세동기" },
    { id: 246, name: "Trigger Nade", price: 1000, tier: "C", kr_name: "트리거 수류탄" },
    { id: 247, name: "Jolt Mine", price: 850, tier: "C", kr_name: "충격 지뢰" },
    { id: 248, name: "Shrapnel Grenade", price: 800, tier: "C", kr_name: "파편 수류탄" },
    { id: 249, name: "Snap Blast Grenade", price: 800, tier: "C", kr_name: "스냅 블래스트 수류탄" },
    { id: 250, name: "Shotgun Parts", price: 700, tier: "D", kr_name: "산탄총 부품" },
    { id: 251, name: "Synthesized Fuel", price: 700, tier: "D", kr_name: "합성 연료" },
    { id: 252, name: "Heavy Gun Parts", price: 700, tier: "D", kr_name: "중량 총기 부품" },
    { id: 253, name: "Medium Gun Parts", price: 700, tier: "D", kr_name: "준중량 총기 부품" },
    { id: 254, name: "Light Gun Parts", price: 700, tier: "D", kr_name: "경량 총기 부품" },
    { id: 255, name: "Vertical Grip I", price: 640, tier: "D", kr_name: "수직 그립 I" },
    { id: 256, name: "Mechanical Components", price: 640, tier: "D", kr_name: "기계 부품" },
    { id: 257, name: "Stable Stock I", price: 640, tier: "D", kr_name: "안정형 개머리판 I" },
    { id: 258, name: "Herbal Bandage", price: 640, tier: "D", kr_name: "약초 붕대" },
    { id: 259, name: "Barricade Kit", price: 640, tier: "D", kr_name: "바리케이드 키트" },
    { id: 260, name: "Diving Goggles", price: 640, tier: "D", kr_name: "다이빙 고글" },
    { id: 261, name: "Frying Pan", price: 640, tier: "D", kr_name: "프라이팬" },
    { id: 262, name: "Dried-Out ARC Resin", price: 640, tier: "D", kr_name: "말라버린 ARC 수지" },
    { id: 263, name: "Pop Trigger", price: 640, tier: "D", kr_name: "팝 트리거" },
    { id: 264, name: "Burned ARC Circuitry", price: 640, tier: "D", kr_name: "타버린 아크 전기회로망" },
    { id: 265, name: "Roots", price: 640, tier: "D", kr_name: "뿌리" },
    { id: 266, name: "Combat Mk. 1", price: 640, tier: "D", kr_name: "전투 마크 1" },
    { id: 267, name: "Tactical Mk. 1", price: 640, tier: "D", kr_name: "전술 마크 1" },
    { id: 268, name: "Damaged Hornet Driver", price: 640, tier: "D", kr_name: "손상된 호넷 드라이버" },
    { id: 269, name: "Olives", price: 640, tier: "D", kr_name: "올리브" },
    { id: 270, name: "Ruined Handcuffs", price: 640, tier: "D", kr_name: "망가진 수갑" },
    { id: 271, name: "Candle Holder", price: 640, tier: "D", kr_name: "양초 홀더" },
    { id: 272, name: "Angled Grip I", price: 640, tier: "D", kr_name: "앵글 그립 I" },
    { id: 273, name: "Degraded ARC Rubber", price: 640, tier: "D", kr_name: "열화된 ARC 고무" },
    { id: 274, name: "Compensator I", price: 640, tier: "D", kr_name: "총구 보정기 I" },
    { id: 275, name: "Muzzle Brake I", price: 640, tier: "D", kr_name: "총구 제동기 I" },
    { id: 276, name: "Rusty ARC Steel", price: 640, tier: "D", kr_name: "녹슨 ARC 강철" },
    { id: 277, name: "Advanced ARC Powercell", price: 640, tier: "D", kr_name: "고급 아크 파워셀" },
    { id: 278, name: "Impure ARC Coolant", price: 640, tier: "D", kr_name: "불순한 ARC 냉각수" },
    { id: 279, name: "Light Shield", price: 640, tier: "D", kr_name: "경량 실드" },
    { id: 280, name: "Ruined Parachute", price: 640, tier: "D", kr_name: "부서진 낙하산" },
    { id: 281, name: "Fireball Burner", price: 640, tier: "D", kr_name: "파이어볼 버너" },
    { id: 282, name: "Faded Photograph", price: 640, tier: "D", kr_name: "빛바랜 사진" },
    { id: 283, name: "Rusted Bolts", price: 640, tier: "D", kr_name: "녹슨 볼트" },
    { id: 284, name: "Tick Pod", price: 640, tier: "D", kr_name: "틱 포드" },
    { id: 285, name: "Tattered ARC Lining", price: 640, tier: "D", kr_name: "해진 ARC 라이닝" },
    { id: 286, name: "Apricot", price: 640, tier: "D", kr_name: "살구" },
    { id: 287, name: "Lemon", price: 640, tier: "D", kr_name: "레몬" },
    { id: 288, name: "Ruined Baton", price: 640, tier: "D", kr_name: "망가진 진압봉" },
    { id: 289, name: "Metal Brackets", price: 640, tier: "D", kr_name: "금속 브래킷" },
    { id: 290, name: "Household Cleaner", price: 640, tier: "D", kr_name: "가정용 세제" },
    { id: 291, name: "Prickly Pear", price: 640, tier: "D", kr_name: "천년초" },
    { id: 292, name: "Durable Cloth", price: 640, tier: "D", kr_name: "질긴 천" },
    { id: 293, name: "Shotgun Choke I", price: 640, tier: "D", kr_name: "산탄총 초크 I" },
    { id: 294, name: "Damaged ARC Motion Core", price: 640, tier: "D", kr_name: "손상된 아크 모션 코어" },
    { id: 295, name: "Dog Collar", price: 640, tier: "D", kr_name: "개 목걸이" },
    { id: 296, name: "Tattered Clothes", price: 640, tier: "D", kr_name: "해진 옷" },
    { id: 297, name: "Electrical Components", price: 640, tier: "D", kr_name: "전기 부품" },
    { id: 298, name: "Binoculars", price: 640, tier: "D", kr_name: "쌍안경" },
    { id: 299, name: "Expired Respirator", price: 640, tier: "D", kr_name: "유통기한 지난 호흡기" },
    { id: 300, name: "Ruined Tactical Vest", price: 640, tier: "D", kr_name: "망가진 전술 조끼" },
    { id: 301, name: "Noisemaker", price: 640, tier: "D", kr_name: "소음기" },
    { id: 302, name: "Camera Lens", price: 640, tier: "D", kr_name: "카메라 렌즈" },
    { id: 303, name: "Ice Cream Scooper", price: 640, tier: "D", kr_name: "아이스크림 스쿠퍼" },
    { id: 304, name: "Torn Blanket", price: 640, tier: "D", kr_name: "찢어진 담요" },
    { id: 305, name: "Flame Spray", price: 640, tier: "D", kr_name: "화염 스프레이" },
    { id: 306, name: "Seeker Grenade", price: 640, tier: "D", kr_name: "추적 수류탄" },
    { id: 307, name: "Extended Light Mag I", price: 640, tier: "D", kr_name: "확장형 경량 탄창 I" },
    { id: 308, name: "Extended Medium Mag I", price: 640, tier: "D", kr_name: "확장형 준중량 탄창 I" },
    { id: 309, name: "Looting Mk. 1", price: 640, tier: "D", kr_name: "노획 마크 1" },
    { id: 310, name: "Extended Shotgun Mag I", price: 640, tier: "D", kr_name: "확장형 산탄총 탄창 I" },
    { id: 311, name: "Shield Recharger", price: 520, tier: "D", kr_name: "실드 충전기" },
    { id: 312, name: "Syringe", price: 500, tier: "D", kr_name: "주사기" },
    { id: 313, name: "Moss", price: 500, tier: "D", kr_name: "이끼" },
    { id: 314, name: "Processor", price: 500, tier: "D", kr_name: "프로세서" },
    { id: 315, name: "Sensors", price: 500, tier: "D", kr_name: "센서" },
    { id: 316, name: "Voltage Converter", price: 500, tier: "D", kr_name: "변압기" },
    { id: 317, name: "Rope", price: 500, tier: "D", kr_name: "밧줄" },
    { id: 318, name: "Speaker Component", price: 500, tier: "D", kr_name: "스피커 부품" },
    { id: 319, name: "Pulse Mine", price: 470, tier: "D", kr_name: "펄스 지뢰" },
    { id: 320, name: "Simple Gun Parts", price: 330, tier: "D", kr_name: "간단한 총기 부품" },
    { id: 321, name: "Duct Tape", price: 300, tier: "D", kr_name: "덕트 테이프" },
    { id: 322, name: "Torch Ginger", price: 300, tier: "D", kr_name: "토치 진저" },
    { id: 323, name: "Oil", price: 300, tier: "D", kr_name: "기름" },
    { id: 324, name: "Steel Spring", price: 300, tier: "D", kr_name: "강철 스프링" },
    { id: 325, name: "Canister", price: 300, tier: "D", kr_name: "캔" },
    { id: 326, name: "Li'l Smoke Grenade", price: 300, tier: "D", kr_name: "꼬마 연막 수류탄" },
    { id: 327, name: "Gas Grenade Trap", price: 300, tier: "D", kr_name: "가스 수류탄 트랩" },
    { id: 328, name: "Great Mullein", price: 300, tier: "D", kr_name: "우단담배풀" },
    { id: 329, name: "Magnet", price: 300, tier: "D", kr_name: "자석" },
    { id: 330, name: "Adrenaline Shot", price: 300, tier: "D", kr_name: "아드레날린 주사" },
    { id: 331, name: "Damaged ARC Powercell", price: 293, tier: "D", kr_name: "손상된 아크 파워셀" },
    { id: 332, name: "Crude Explosives", price: 270, tier: "D", kr_name: "조악한 폭발물" },
    { id: 333, name: "Volcanic Rock", price: 270, tier: "D", kr_name: "화산암" },
    { id: 334, name: "Crumpled Plastic Bottle", price: 270, tier: "D", kr_name: "구겨진 플라스틱병" },
    { id: 335, name: "Damaged Fireball Burner", price: 270, tier: "D", kr_name: "손상된 파이어볼 버너" },
    { id: 336, name: "Damaged Wasp Driver", price: 270, tier: "D", kr_name: "손상된 와스프 드라이버" },
    { id: 337, name: "Broken Handcuffs", price: 270, tier: "D", kr_name: "고장난 수갑" },
    { id: 338, name: "Light Impact Grenade", price: 270, tier: "D", kr_name: "경량 충돌 수류탄" },
    { id: 339, name: "Gas Grenade", price: 270, tier: "D", kr_name: "가스 수류탄" },
    { id: 340, name: "Ruined Augment", price: 270, tier: "D", kr_name: "망가진 증강" },
    { id: 341, name: "Gas Mine", price: 270, tier: "D", kr_name: "가스 지뢰" },
    { id: 342, name: "Damaged Tick Pod", price: 270, tier: "D", kr_name: "손상된 틱 포드" },
    { id: 343, name: "Remote Raider Flare", price: 270, tier: "D", kr_name: "원격 레이더 조명탄" },
    { id: 344, name: "ARC Powercell", price: 270, tier: "D", kr_name: "아크 파워셀" },
    { id: 345, name: "Door Blocker", price: 270, tier: "D", kr_name: "문 차단기" },
    { id: 346, name: "Number Plate", price: 270, tier: "D", kr_name: "번호판" },
    { id: 347, name: "Bandage", price: 250, tier: "D", kr_name: "붕대" },
    { id: 348, name: "Launcher Ammo", price: 250, tier: "D", kr_name: "발사기 탄약" },
    { id: 349, name: "Battery", price: 250, tier: "D", kr_name: "배터리" },
    { id: 350, name: "Wires", price: 200, tier: "D", kr_name: "전선" },
    { id: 351, name: "ARC Alloy", price: 200, tier: "D", kr_name: "아크 합금" },
    { id: 352, name: "Green Light Stick", price: 150, tier: "D", kr_name: "초록색 야광봉" },
    { id: 353, name: "Blue Light Stick", price: 150, tier: "D", kr_name: "파란색 야광봉" },
    { id: 354, name: "Yellow Light Stick", price: 150, tier: "D", kr_name: "노란색 야광봉" },
    { id: 355, name: "Red Light Stick", price: 150, tier: "D", kr_name: "빨간색 야광봉" },
    { id: 356, name: "Agave Juice", price: 123, tier: "D", kr_name: "아가베 주스" },
    { id: 357, name: "Dam Testing Annex Key", price: 100, tier: "D", kr_name: "댐 시험 별관 열쇠" },
    { id: 358, name: "Blue Gate Village Key", price: 100, tier: "D", kr_name: "블루 게이트 마을 열쇠" },
    { id: 359, name: "Patrol Car Key", price: 100, tier: "D", kr_name: "순찰차 열쇠" },
    { id: 360, name: "Spaceport Control Tower Key", price: 100, tier: "D", kr_name: "우주 공항 관제탑 열쇠" },
    { id: 361, name: "Stella Montis Archives Key", price: 100, tier: "D", kr_name: "스텔라 몬티스 기록 보관소 열쇠" },
    { id: 362, name: "Stella Montis Assembly Admin Key", price: 100, tier: "D", kr_name: "스텔라 몬티스 조립 관리 열쇠" },
    { id: 363, name: "Stella Montis Security Checkpoint Key", price: 100, tier: "D", kr_name: "스텔라 몬티스 보안 검문소 열쇠" },
    { id: 364, name: "Blue Gate Cellar Key", price: 100, tier: "D", kr_name: "블루 게이트 지하실 열쇠" },
    { id: 365, name: "Blue Gate Communication Tower Key", price: 100, tier: "D", kr_name: "블루 게이트 통신탑 열쇠" },
    { id: 366, name: "Buried City Residential Master Key", price: 100, tier: "D", kr_name: "매몰된 도시 주거 마스터 키" },
    { id: 367, name: "Spaceport Outskirts Bunker Key", price: 100, tier: "D", kr_name: "우주 공항 외곽 벙커 열쇠" },
    { id: 368, name: "Spaceport Container Storage Key", price: 100, tier: "D", kr_name: "우주 공항 컨테이너 창고 열쇠" },
    { id: 369, name: "Dam Control Center Tower Key", price: 100, tier: "D", kr_name: "댐 통제 센터 타워 열쇠" },
    { id: 370, name: "Buried City JKV Employee Access Card", price: 100, tier: "D", kr_name: "매몰된 도시 JKV 직원 출입 카드" },
    { id: 371, name: "Dam Surveillance Key", price: 100, tier: "D", kr_name: "댐 감시 열쇠" },
    { id: 372, name: "Dam Utility Key", price: 100, tier: "D", kr_name: "댐 유틸리티 열쇠" },
    { id: 373, name: "Spaceport Trench Tower Key", price: 100, tier: "D", kr_name: "우주 공항 트렌치 타워 열쇠" },
    { id: 374, name: "Spaceport Warehouse Key", price: 100, tier: "D", kr_name: "우주 공항 창고 열쇠" },
    { id: 375, name: "Free Loadout Augment", price: 100, tier: "D", kr_name: "무료 로드아웃 증강물" },
    { id: 376, name: "Assorted Seeds", price: 100, tier: "D", kr_name: "잡다한 씨앗" },
    { id: 377, name: "Blue Gate Confiscation Room Key", price: 100, tier: "D", kr_name: "블루 게이트 압수품 보관실 열쇠" },
    { id: 378, name: "Stella Montis Medical Storage Key", price: 100, tier: "D", kr_name: "스텔라 몬티스 의료 보관소 열쇠" },
    { id: 379, name: "Dam Staff Room Key", price: 100, tier: "D", kr_name: "댐 직원실 열쇠" },
    { id: 380, name: "Buried City Hospital Key", price: 100, tier: "D", kr_name: "매몰된 도시 병원 열쇠" },
    { id: 381, name: "Buried City Town Hall Key", price: 100, tier: "D", kr_name: "매몰된 도시 시청 열쇠" },
    { id: 382, name: "Metal Parts", price: 75, tier: "D", kr_name: "금속 부품" },
    { id: 383, name: "Plastic Parts", price: 60, tier: "D", kr_name: "플라스틱 부품" },
    { id: 384, name: "Fabric", price: 50, tier: "D", kr_name: "직물" },
    { id: 385, name: "Chemicals", price: 50, tier: "D", kr_name: "화학품" },
    { id: 386, name: "Rubber Parts", price: 50, tier: "D", kr_name: "고무 부품" },
    { id: 387, name: "Shotgun ammo", price: 20, tier: "D", kr_name: "산탄총 탄약" },
    { id: 388, name: "Heavy Ammo", price: 12, tier: "D", kr_name: "중량 탄약" },
    { id: 389, name: "Medium Ammo", price: 6, tier: "D", kr_name: "준중량 탄약" },
    { id: 390, name: "Energy Clip", price: 5, tier: "D", kr_name: "에너지 클립" },
    { id: 391, name: "Light Ammo", price: 4, tier: "D", kr_name: "경량 탄약" }
];